### ISSUE TITLE
Azure Webroles fail to start with 'Please provide a thumbprint for this machine' error

### ISSUE THREAD

**Issue by daniefvh** [MRCollective/AzureWebFarm.OctopusDeploy#32]
We are running Octopus Deploy 2.6.0.778 (last 2.x version). When our web roles are initializing it fails with the following error:

```
Exception string System.Exception: Non-zero exit code returned (100). Stdout: Octopus Deploy: Tentacle version 3.1.4 (3.1.4+Branch.master.Sha.3510f96241b0bb85f7189448bb7fef417340ebf8)
Checking connectivity on the server communications port 10943...
-------------------------------------------------------------------------------
Error: There was a problem with your request.

 - Please provide a thumbprint for this machine.

-------------------------------------------------------------------------------
Full error details are available in the log files.
At: D:\Windows\system32\config\systemprofile\AppData\Local\Octopus\Logs
===============================================================================
There was a problem with your request.

 - Please provide a thumbprint for this machine.

Octopus.Client.Exceptions.OctopusValidationException: There was a problem with your request.

 - Please provide a thumbprint for this machine.

   at Octopus.Client.OctopusClient.DispatchRequest[TResponseResource](OctopusRequest request, Boolean readResponse) in Y:\work\refs\tags\3.1.4\source\Octopus.Client\OctopusClient.cs:line 457
   at Octopus.Client.OctopusClient.Create[TResource](String path, TResource resource) in Y:\work\refs\tags\3.1.4\source\Octopus.Client\OctopusClient.cs:line 150
   at Octopus.Client.OctopusRepository.BasicRepository`1.Create(TResource resource) in Y:\work\refs\tags\3.1.4\source\Octopus.Client\OctopusRepository.cs:line 259
   at Octopus.Tentacle.Commands.RegisterMachineCommand.Start() in Y:\work\refs\tags\3.1.4\source\Octopus.Tentacle\Commands\RegisterMachineCommand.cs:line 103
   at Octopus.Shared.Startup.AbstractCommand.Octopus.Shared.Startup.ICommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in Y:\work\refs\tags\3.1.4\source\Octopus.Shared\Startup\AbstractCommand.cs:line 57
   at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown) in Y:\work\refs\tags\3.1.4\source\Octopus.Shared\Startup\ConsoleHost.cs:line 72
   at Octopus.Shared.Startup.OctopusProgram.Run() in Y:\work\refs\tags\3.1.4\source\Octopus.Shared\Startup\OctopusProgram.cs:line 87
 StdErr: 
   at AzureWebFarm.OctopusDeploy.Infrastructure.ProcessRunner.Run(String executable, String arguments)
```

**Comment by daniefvh** [comment]
Managed to figure this one out by myself eventually:

In the `startup.ps1` in the WebFarm project, it has the following line which specifies which version of the Octopus tentacle to download.
`$TentacleDownloadPath = "https://octopusdeploy.com/downloads/latest/OctopusTentacle64"`
however since we are running version 2 server and the "latest" version in version 3, it will download a version 3 tentacle. Did some googleing and it appears version 3 tentacles can't talk to version 2 servers.

So the Fix is this:
1. Change the  $TentacleDownloadPath to the last version 2 tentacle version: 
`$TentacleDownloadPath = "http://download.octopusdeploy.com/octopus/Octopus.Tentacle.2.6.5.1010-x64.msi"`
2. Create a new deployment package and upload to Azure.

Hope this saves someone else some time!

**Comment by robdmoore** [comment]
Thanks Dan!
